// This file is auto-generated by build-prayer-data.js. Do not edit manually.

export const detailedPrayerData: { [key: string]: any } = {
  "aleph-prayers": [
    {
      "title": "Adon Olam",
      "hebrew": "אֲדוֹן עוֹלָם"
    },
    {
      "title": "Ad-i Melech",
      "hebrew": "אֲדֹנָי מֶלֶךְ"
    },
    {
      "title": "Ad-i, S'fatai Tiftach",
      "hebrew": "אֲדֹנָי, שְׂפָתַי תִּפְתָּח"
    },
    {
      "title": "Adir Hu",
      "hebrew": "אַדִּיר הוּא"
    },
    {
      "title": "Ahava Rabbah",
      "hebrew": "אַהֲבָה רַבָּה"
    },
    {
      "title": "Ahavat Olam",
      "hebrew": "אַהֲבַת עוֹלָם"
    },
    {
      "title": "Akdamut Millin",
      "hebrew": "אַקְדָמוּת מִלִּין"
    },
    {
      "title": "Al Tira",
      "hebrew": "אַל תִּירָא"
    },
    {
      "title": "Anim Zemirot",
      "hebrew": "אַנְעִים זְמִירוֹת"
    },
    {
      "title": "Areshet Sefateinu",
      "hebrew": "אֲרֶשֶׁת שְׂפָתֵינוּ"
    },
    {
      "title": "Asher Yatzar",
      "hebrew": "אֲשֶׁר יָצַר"
    },
    {
      "title": "Ashrei",
      "hebrew": "אַשְׁרֵי"
    },
    {
      "title": "Ata Chonantanu",
      "hebrew": "אַתָּה חוֹנַנְתָּנוּ"
    },
    {
      "title": "Ata Kadosh",
      "hebrew": "אַתָּה קָדוֹשׁ"
    },
    {
      "title": "Atem Re'item",
      "hebrew": "אַתֶּם רְאִיתֶם"
    },
    {
      "title": "Av Harachamim",
      "hebrew": "אב הרחמים"
    },
    {
      "title": "Avinu Malkeinu",
      "hebrew": "אָבִינוּ מַלְכֵּנוּ"
    },
    {
      "title": "Avot",
      "hebrew": "אָבוֹת"
    },
    {
      "title": "Az Yashir Moshe",
      "hebrew": "אָז יָשִׁיר מֹשֶׁה"
    },
    {
      "title": "Ein Keloheinu",
      "hebrew": "אֵין כֵּאלֹהֵינוּ"
    },
    {
      "title": "Eilu Devarim",
      "hebrew": "אֵלּוּ דְבָרִים"
    },
    {
      "title": "Eizehu Mekoman",
      "hebrew": "אֵיזֶהוּ מְקוֹמָן"
    },
    {
      "title": "El Adon",
      "hebrew": "אֵל אָדוֹן"
    },
    {
      "title": "El Erech Apayim",
      "hebrew": "אֵל אֶרֶךְ אַפַּיִם"
    },
    {
      "title": "El Malei Rachamim",
      "hebrew": "אֵל מָלֵא רַחֲמִים"
    },
    {
      "title": "Elohai Neshama",
      "hebrew": "אֱלֹהַי נְשָׁמָה"
    },
    {
      "title": "Elohai, Netzor",
      "hebrew": "אֱלֹהַי, נְצֹר"
    },
    {
      "title": "Emet Ve'emunah",
      "hebrew": "אֱמֶת וֶאֱמוּנָה"
    },
    {
      "title": "Emet Veyatziv",
      "hebrew": "אֱמֶת וְיַצִיב"
    },
    {
      "title": "Omnam Ken",
      "hebrew": "אָמְנָם כֵּן"
    }
  ],
  "beis-prayers": [
    {
      "title": "Bameh Madlikin",
      "hebrew": "בַּמֶה מַדְלִיקִין"
    },
    {
      "title": "Bar Yochai",
      "hebrew": "בַּר יוֹחַאי"
    },
    {
      "title": "Barechu",
      "hebrew": "בָּרְכוּ"
    },
    {
      "title": "Baruch Ad-ai Ba'yom",
      "hebrew": "בָּרוּךְ ה' בַּיּוֹם"
    },
    {
      "title": "Baruch Ad-ai L'Olam",
      "hebrew": "בָּרוּךְ ה' לְעוֹלָם"
    },
    {
      "title": "Baruch Ad-ai Tzuri",
      "hebrew": "בָּרוּךְ ה' צוּרִי"
    },
    {
      "title": "Baruch Hamakom",
      "hebrew": "בָּרוּךְ הַמָּקוֹם"
    },
    {
      "title": "Baruch She'amar",
      "hebrew": "בָּרוּךְ שֶׁאָמַר"
    },
    {
      "title": "Ben Adamah",
      "hebrew": "בֶּן אָדָם"
    },
    {
      "title": "B'fi Yesharim",
      "hebrew": "בְּפִי יְשָׁרִים"
    },
    {
      "title": "Birkat HaGomel",
      "hebrew": "בִּרְכַּת הַגּוֹמֵל"
    },
    {
      "title": "Birkat Hagefen",
      "hebrew": "בִּרְכַּת הַגֶפֶן"
    },
    {
      "title": "Birkat Hachamah",
      "hebrew": "בִּרְכַּת הַחַמָּה"
    },
    {
      "title": "Birkat Ha'ilanot",
      "hebrew": "בִּרְכַּת הָאִילָנוֹת"
    },
    {
      "title": "Birkat HaLevana",
      "hebrew": "בִּרְכַּת הַלְּבָנָה"
    },
    {
      "title": "Birkat Hamazon",
      "hebrew": "בִּרְכַּת הַמָּזוֹן"
    },
    {
      "title": "Birkat Hamotzi",
      "hebrew": "בִּרְכַּת הַמּוֹצִיא"
    },
    {
      "title": "Birkat M'ein Shalosh",
      "hebrew": "בִּרְכַּת מֵעֵין שָׁלשׁ"
    },
    {
      "title": "Birkot Hashachar",
      "hebrew": "בִּרְכוֹת הַשַּׁחַר"
    },
    {
      "title": "Birkot Hatorah",
      "hebrew": "בִּרְכוֹת הַתּוֹרָה"
    },
    {
      "title": "B'Moza'ei Yom Menucha",
      "hebrew": "בְּמוֹצָאֵי יוֹם מְנוּחָה"
    },
    {
      "title": "Borei Minei Mezonot",
      "hebrew": "בּוֹרֵא מִינֵי מְזוֹנוֹת"
    },
    {
      "title": "Borei Minei Vesamim",
      "hebrew": "בּוֹרֵא מִינֵי בְשָׂמִים"
    },
    {
      "title": "Borei Nefashot",
      "hebrew": "בּוֹרֵא נְפָשׁוֹת"
    },
    {
      "title": "Borei Pri Ha'adamah",
      "hebrew": "בּוֹרֵא פְּרִי הָאֲדָמָה"
    },
    {
      "title": "Borei Pri Ha'etz",
      "hebrew": "בּוֹרֵא פְּרִי הָעֵץ"
    },
    {
      "title": "B'rich Sh'mei",
      "hebrew": "בְּרִיךְ שְׁמֵהּ"
    },
    {
      "title": "B'rov Am",
      "hebrew": "בְּרָב עָם"
    },
    {
      "title": "B'sefer Chayim",
      "hebrew": "בְּסֵפֶר חַיִים"
    },
    {
      "title": "B'shem Hashem",
      "hebrew": "בְּשֵׁם ה'"
    },
    {
      "title": "B'tzeit Yisrael",
      "hebrew": "בְּצֵאת יִשְׂרָאֵל"
    }
  ],
  "gimel-prayers": [
    {
      "title": "Gadelu",
      "hebrew": "גַּדְּלוּ"
    },
    {
      "title": "Gadol Ad-ai",
      "hebrew": "גָּדוֹל ה'"
    },
    {
      "title": "Gam Ki Elech",
      "hebrew": "גַּם כִּי אֵלֵךְ"
    },
    {
      "title": "Gazalnu",
      "hebrew": "גָּזַלְנוּ"
    },
    {
      "title": "G'mol Al Avd'cha",
      "hebrew": "גְּמֹל עַל עַבְדְּךָ"
    },
    {
      "title": "Gevohah Mi-kol Gevohim",
      "hebrew": "גָּבוֹהַ מִכָּל גְּבֹהִים"
    },
    {
      "title": "Gevurotecha Yechavu",
      "hebrew": "גְּבוּרוֹתֶיךָ יְחַוּוּ"
    }
  ],
  "40-0rwa": {
    "prayer-title": "Modei Ani",
    "Introduction": "Give thanks upon waking",
    "Instruction": "Said with hands clasped together",
    "prayer-id": "40-0rwa",
    "Word Mappings": {
      "0": {
        "hebrew": "מוֹדֶה אֲנִי",
        "english": "I thank",
        "detailed-array": [
          [
            1,
            0
          ],
          [
            0,
            1
          ]
        ]
      },
      "1": {
        "hebrew": "לְפָנֶֽיךָ",
        "english": "before You",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "2": {
        "hebrew": "מֶֽלֶךְ חַי וְקַיָּם",
        "english": "King living and eternal",
        "detailed-array": [
          [
            0,
            0
          ],
          [
            1,
            1
          ],
          [
            2,
            [
              2,
              3
            ]
          ]
        ]
      },
      "3": {
        "hebrew": "שֶׁהֶחֱזַֽרְתָּ בִּי נִשְׁמָתִי",
        "english": "that You returned in me my soul",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ],
          [
            1,
            [
              3,
              4
            ]
          ],
          [
            2,
            [
              5,
              6
            ]
          ]
        ]
      },
      "4": {
        "hebrew": "בְּחֶמְלָה",
        "english": "with compassion",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "5": {
        "hebrew": "רַבָּה אֱמוּנָתֶֽךָ",
        "english": "great is Your faithfulness",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ],
          [
            1,
            [
              2,
              3
            ]
          ]
        ]
      }
    }
  }
};
