// This file is auto-generated by build-prayer-data.js. Do not edit manually.

export const detailedPrayerData: { [key: string]: any } = {
  "1-0rw1": {
    "prayer-title": "Elohai Neshamah (My God, the Soul)",
    "version": "1.0.0",
    "date_modified": "2025-08-31T02:30:52-05:00",
    "Introduction": "A prayer acknowledging the purity of the soul, recited upon waking.",
    "Instruction": "Recited in the morning blessings, traditionally upon waking.",
    "prayer-id": "1-0rw1",
    "Word Mappings": {
      "0": {
        "hebrew": "אֱלֹהַי,",
        "english": "My God,",
        "transliteration": "Elohai,",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "1": {
        "hebrew": "נְשָׁמָה",
        "english": "the soul",
        "transliteration": "neshamah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "2": {
        "hebrew": "שֶׁנָּתַתָּ",
        "english": "which You have given",
        "transliteration": "shenatata",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2,
              3
            ]
          ]
        ]
      },
      "3": {
        "hebrew": "בִּי",
        "english": "in me",
        "transliteration": "bi",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "4": {
        "hebrew": "טְהוֹרָה",
        "english": "pure",
        "transliteration": "t'horah",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "5": {
        "hebrew": "הִיא.",
        "english": "it is.",
        "transliteration": "hi.",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "6": {
        "hebrew": "אַתָּה",
        "english": "You",
        "transliteration": "Atah",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "7": {
        "hebrew": "בְרָאתָהּ,",
        "english": "created it,",
        "transliteration": "v'ratah,",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "8": {
        "hebrew": "אַתָּה",
        "english": "You",
        "transliteration": "Atah",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "9": {
        "hebrew": "יְצַרְתָּהּ,",
        "english": "formed it,",
        "transliteration": "y'tzartah,",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "10": {
        "hebrew": "אַתָּה",
        "english": "You",
        "transliteration": "Atah",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "11": {
        "hebrew": "נְפַחְתָּהּ",
        "english": "breathed it",
        "transliteration": "n'fachtah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "12": {
        "hebrew": "בִּי,",
        "english": "into me,",
        "transliteration": "bi,",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "13": {
        "hebrew": "וְאַתָּה",
        "english": "and You",
        "transliteration": "v'Atah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "14": {
        "hebrew": "מְשַׁמְּרָהּ",
        "english": "preserve it",
        "transliteration": "m'shamrah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "15": {
        "hebrew": "בְּקִרְבִּי,",
        "english": "within me,",
        "transliteration": "b'kirbi,",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "16": {
        "hebrew": "וְאַתָּה",
        "english": "and You",
        "transliteration": "v'Atah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "17": {
        "hebrew": "עָתִיד",
        "english": "will eventually",
        "transliteration": "atid",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "18": {
        "hebrew": "לִטְּלָהּ",
        "english": "take it",
        "transliteration": "lit'lah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "19": {
        "hebrew": "מִמֶּנִּי,",
        "english": "from me,",
        "transliteration": "mimeni,",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "20": {
        "hebrew": "וּלְהַחֲזִירָהּ",
        "english": "and to restore it",
        "transliteration": "ul'hachazirah",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2,
              3
            ]
          ]
        ]
      },
      "21": {
        "hebrew": "בִּי",
        "english": "to me",
        "transliteration": "bi",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "22": {
        "hebrew": "לֶעָתִיד",
        "english": "in the time",
        "transliteration": "le'atid",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "23": {
        "hebrew": "לָבוֹא.",
        "english": "to come.",
        "transliteration": "lavo.",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "24": {
        "hebrew": "כָּל",
        "english": "So long",
        "transliteration": "Kol",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "25": {
        "hebrew": "זְמַן",
        "english": "as",
        "transliteration": "z'man",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "26": {
        "hebrew": "שֶׁהַנְּשָׁמָה",
        "english": "the soul",
        "transliteration": "shehaneshamah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "27": {
        "hebrew": "בְקִרְבִּי,",
        "english": "is within me,",
        "transliteration": "b'kirbi,",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "28": {
        "hebrew": "מוֹדֶה",
        "english": "thank",
        "transliteration": "modeh",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "29": {
        "hebrew": "אֲנִי",
        "english": "I",
        "transliteration": "ani",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "30": {
        "hebrew": "לְפָנֶיךָ,",
        "english": "You,",
        "transliteration": "l'fanekha,",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "31": {
        "hebrew": "יְיָ",
        "english": "ETERNAL,",
        "transliteration": "Ad-nai,",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "32": {
        "hebrew": "אֱלֹהַי",
        "english": "my God",
        "transliteration": "Elohai",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "33": {
        "hebrew": "וֵאלֹהֵי",
        "english": "and God of",
        "transliteration": "v'Elohei",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "34": {
        "hebrew": "אֲבוֹתַי,",
        "english": "my ancestors,",
        "transliteration": "avotai,",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "35": {
        "hebrew": "רִבּוֹן",
        "english": "Master of",
        "transliteration": "Ribon",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "36": {
        "hebrew": "כָּל",
        "english": "all",
        "transliteration": "kol",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "37": {
        "hebrew": "הַמַּעֲשִׂים,",
        "english": "works,",
        "transliteration": "hama'asim,",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "38": {
        "hebrew": "אֲדוֹן",
        "english": "Lord of",
        "transliteration": "Adon",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "39": {
        "hebrew": "כָּל",
        "english": "all",
        "transliteration": "kol",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "40": {
        "hebrew": "הַנְּשָׁמוֹת.",
        "english": "souls.",
        "transliteration": "haneshamot.",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "41": {
        "hebrew": "בָּרוּךְ",
        "english": "Blessed",
        "transliteration": "Baruch",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "42": {
        "hebrew": "אַתָּה",
        "english": "You are",
        "transliteration": "atah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "43": {
        "hebrew": "יְיָ,",
        "english": "ETERNAL,",
        "transliteration": "Ad-nai,",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "44": {
        "hebrew": "הַמַּחֲזִיר",
        "english": "Who restores",
        "transliteration": "hamachazir",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "45": {
        "hebrew": "נְשָׁמוֹת",
        "english": "souls",
        "transliteration": "neshamot",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "46": {
        "hebrew": "לִפְגָרִים",
        "english": "to bodies",
        "transliteration": "lifgarim",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "47": {
        "hebrew": "מֵתִים.",
        "english": "dead.",
        "transliteration": "metim.",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      }
    }
  },
  "1-0rwa": {
    "prayer-title": "Asher Yatzar (Who Formed)",
    "version": "1.0.0",
    "date_modified": "2025-08-31T00:55:58-05:00",
    "Introduction": "Blessing for after using the restroom.",
    "Instruction": "Recited after using the restroom and washing one's hands.",
    "prayer-id": "1-0rwa",
    "Word Mappings": {
      "0": {
        "hebrew": "בָּרוּךְ",
        "english": "Blessed",
        "transliteration": "Baruch",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "1": {
        "hebrew": "אַתָּה",
        "english": "You are",
        "transliteration": "atah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "2": {
        "hebrew": "יְיָ",
        "english": "ETERNAL",
        "transliteration": "Ad-nai",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "3": {
        "hebrew": "אֱלֹהֵינוּ",
        "english": "our God",
        "transliteration": "Eloheinu",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "4": {
        "hebrew": "מֶלֶךְ",
        "english": "King",
        "transliteration": "melekh",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "5": {
        "hebrew": "הָעוֹלָם",
        "english": "of the universe",
        "transliteration": "ha'olam",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "6": {
        "hebrew": "אֲשֶׁר",
        "english": "Who",
        "transliteration": "asher",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "7": {
        "hebrew": "יָצַר",
        "english": "formed",
        "transliteration": "yatzar",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "8": {
        "hebrew": "אֶת",
        "english": "the",
        "transliteration": "et",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "9": {
        "hebrew": "הָאָדָם",
        "english": "man",
        "transliteration": "ha'adam",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "10": {
        "hebrew": "בְּחָכְמָה",
        "english": "with wisdom",
        "transliteration": "b'chokhmah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "11": {
        "hebrew": "וּבָרָא",
        "english": "and created",
        "transliteration": "u'vara",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "12": {
        "hebrew": "בוֹ",
        "english": "in him",
        "transliteration": "vo",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "13": {
        "hebrew": "נְקָבִים",
        "english": "many",
        "transliteration": "n'kavim",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "14": {
        "hebrew": "נְקָבִים",
        "english": "openings",
        "transliteration": "n'kavim",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "15": {
        "hebrew": "חֲלוּלִים",
        "english": "and many",
        "transliteration": "chalulim",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "16": {
        "hebrew": "חֲלוּלִים",
        "english": "hollows",
        "transliteration": "chalulim",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "17": {
        "hebrew": "גָּלוּי",
        "english": "It is revealed",
        "transliteration": "Galui",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "18": {
        "hebrew": "וְיָדוּעַ",
        "english": "and known",
        "transliteration": "v'yadua",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "19": {
        "hebrew": "לִפְנֵי",
        "english": "before",
        "transliteration": "lifnei",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "20": {
        "hebrew": "כִסֵּא",
        "english": "the Throne",
        "transliteration": "khisei",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "21": {
        "hebrew": "כְבוֹדֶךָ",
        "english": "of Your Glory",
        "transliteration": "kh'vodekha",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "22": {
        "hebrew": "שֶׁאִם",
        "english": "that if",
        "transliteration": "she'im",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "23": {
        "hebrew": "יִפָּתֵחַ",
        "english": "were to be opened",
        "transliteration": "yipate'ach",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2,
              3
            ]
          ]
        ]
      },
      "24": {
        "hebrew": "אֶחָד",
        "english": "one",
        "transliteration": "echad",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "25": {
        "hebrew": "מֵהֶם",
        "english": "of them",
        "transliteration": "mehem",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "26": {
        "hebrew": "אוֹ",
        "english": "or",
        "transliteration": "o",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "27": {
        "hebrew": "יִסָּתֵם",
        "english": "were to be sealed",
        "transliteration": "yisatem",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2,
              3
            ]
          ]
        ]
      },
      "28": {
        "hebrew": "אֶחָד",
        "english": "one",
        "transliteration": "echad",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "29": {
        "hebrew": "מֵהֶם",
        "english": "of them",
        "transliteration": "mehem",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "30": {
        "hebrew": "אִי",
        "english": "it would be",
        "transliteration": "ee",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "31": {
        "hebrew": "אֶפְשַׁר",
        "english": "impossible",
        "transliteration": "efshar",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "32": {
        "hebrew": "לְהִתְקַיֵּם",
        "english": "to survive",
        "transliteration": "l'hitkayem",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "33": {
        "hebrew": "וְלַעֲמוֹד",
        "english": "and to stand",
        "transliteration": "v'la'amod",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "34": {
        "hebrew": "לְפָנֶיךָ",
        "english": "before You",
        "transliteration": "l'fanekha",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "35": {
        "hebrew": "בָּרוּךְ",
        "english": "Blessed",
        "transliteration": "Baruch",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "36": {
        "hebrew": "אַתָּה",
        "english": "You are",
        "transliteration": "atah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "37": {
        "hebrew": "יְיָ",
        "english": "ETERNAL",
        "transliteration": "Ad-nai",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "38": {
        "hebrew": "רוֹפֵא",
        "english": "Who heals",
        "transliteration": "rofeh",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "39": {
        "hebrew": "כָל",
        "english": "all",
        "transliteration": "khol",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "40": {
        "hebrew": "בָּשָׂר",
        "english": "flesh",
        "transliteration": "basar",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "41": {
        "hebrew": "וּמַפְלִיא",
        "english": "and performs",
        "transliteration": "u'mafli",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "42": {
        "hebrew": "לַעֲשׂוֹת",
        "english": "wonders",
        "transliteration": "la'asot",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      }
    }
  },
  "aleph-prayers": [
    {
      "title": "Adon Olam",
      "hebrew": "אֲדוֹן עוֹלָם"
    },
    {
      "title": "Ad-i Melech",
      "hebrew": "אֲדֹנָי מֶלֶךְ"
    },
    {
      "title": "Ad-i, S'fatai Tiftach",
      "hebrew": "אֲדֹנָי, שְׂפָתַי תִּפְתָּח"
    },
    {
      "title": "Adir Hu",
      "hebrew": "אַדִּיר הוּא"
    },
    {
      "title": "Ahava Rabbah",
      "hebrew": "אַהֲבָה רַבָּה"
    },
    {
      "title": "Ahavat Olam",
      "hebrew": "אַהֲבַת עוֹלָם"
    },
    {
      "title": "Akdamut Millin",
      "hebrew": "אַקְדָמוּת מִלִּין"
    },
    {
      "title": "Al Tira",
      "hebrew": "אַל תִּירָא"
    },
    {
      "title": "Anim Zemirot",
      "hebrew": "אַנְעִים זְמִירוֹת"
    },
    {
      "title": "Areshet Sefateinu",
      "hebrew": "אֲרֶשֶׁת שְׂפָתֵינוּ"
    },
    {
      "title": "Asher Yatzar",
      "hebrew": "אֲשֶׁר יָצַר"
    },
    {
      "title": "Ashrei",
      "hebrew": "אַשְׁרֵי"
    },
    {
      "title": "Ata Chonantanu",
      "hebrew": "אַתָּה חוֹנַנְתָּנוּ"
    },
    {
      "title": "Ata Kadosh",
      "hebrew": "אַתָּה קָדוֹשׁ"
    },
    {
      "title": "Atem Re'item",
      "hebrew": "אַתֶּם רְאִיתֶם"
    },
    {
      "title": "Av Harachamim",
      "hebrew": "אב הרחמים"
    },
    {
      "title": "Avinu Malkeinu",
      "hebrew": "אָבִינוּ מַלְכֵּנוּ"
    },
    {
      "title": "Avot",
      "hebrew": "אָבוֹת"
    },
    {
      "title": "Az Yashir Moshe",
      "hebrew": "אָז יָשִׁיר מֹשֶׁה"
    },
    {
      "title": "Ein Keloheinu",
      "hebrew": "אֵין כֵּאלֹהֵינוּ"
    },
    {
      "title": "Eilu Devarim",
      "hebrew": "אֵלּוּ דְבָרִים"
    },
    {
      "title": "Eizehu Mekoman",
      "hebrew": "אֵיזֶהוּ מְקוֹמָן"
    },
    {
      "title": "El Adon",
      "hebrew": "אֵל אָדוֹן"
    },
    {
      "title": "El Erech Apayim",
      "hebrew": "אֵל אֶרֶךְ אַפַּיִם"
    },
    {
      "title": "El Malei Rachamim",
      "hebrew": "אֵל מָלֵא רַחֲמִים"
    },
    {
      "title": "Elohai Neshama",
      "hebrew": "אֱלֹהַי נְשָׁמָה"
    },
    {
      "title": "Elohai, Netzor",
      "hebrew": "אֱלֹהַי, נְצֹר"
    },
    {
      "title": "Emet Ve'emunah",
      "hebrew": "אֱמֶת וֶאֱמוּנָה"
    },
    {
      "title": "Emet Veyatziv",
      "hebrew": "אֱמֶת וְיַצִיב"
    },
    {
      "title": "Omnam Ken",
      "hebrew": "אָמְנָם כֵּן"
    }
  ],
  "beis-prayers": [
    {
      "title": "Bameh Madlikin",
      "hebrew": "בַּמֶה מַדְלִיקִין"
    },
    {
      "title": "Bar Yochai",
      "hebrew": "בַּר יוֹחַאי"
    },
    {
      "title": "Barechu",
      "hebrew": "בָּרְכוּ"
    },
    {
      "title": "Baruch Ad-ai Ba'yom",
      "hebrew": "בָּרוּךְ ה' בַּיּוֹם"
    },
    {
      "title": "Baruch Ad-ai L'Olam",
      "hebrew": "בָּרוּךְ ה' לְעוֹלָם"
    },
    {
      "title": "Baruch Ad-ai Tzuri",
      "hebrew": "בָּרוּךְ ה' צוּרִי"
    },
    {
      "title": "Baruch Hamakom",
      "hebrew": "בָּרוּךְ הַמָּקוֹם"
    },
    {
      "title": "Baruch She'amar",
      "hebrew": "בָּרוּךְ שֶׁאָמַר"
    },
    {
      "title": "Ben Adamah",
      "hebrew": "בֶּן אָדָם"
    },
    {
      "title": "B'fi Yesharim",
      "hebrew": "בְּפִי יְשָׁרִים"
    },
    {
      "title": "Birkat HaGomel",
      "hebrew": "בִּרְכַּת הַגּוֹמֵל"
    },
    {
      "title": "Birkat Hagefen",
      "hebrew": "בִּרְכַּת הַגֶפֶן"
    },
    {
      "title": "Birkat Hachamah",
      "hebrew": "בִּרְכַּת הַחַמָּה"
    },
    {
      "title": "Birkat Ha'ilanot",
      "hebrew": "בִּרְכַּת הָאִילָנוֹת"
    },
    {
      "title": "Birkat HaLevana",
      "hebrew": "בִּרְכַּת הַלְּבָנָה"
    },
    {
      "title": "Birkat Hamazon",
      "hebrew": "בִּרְכַּת הַמָּזוֹן"
    },
    {
      "title": "Birkat Hamotzi",
      "hebrew": "בִּרְכַּת הַמּוֹצִיא"
    },
    {
      "title": "Birkat M'ein Shalosh",
      "hebrew": "בִּרְכַּת מֵעֵין שָׁלשׁ"
    },
    {
      "title": "Birkot Hashachar",
      "hebrew": "בִּרְכוֹת הַשַּׁחַר"
    },
    {
      "title": "Birkot Hatorah",
      "hebrew": "בִּרְכוֹת הַתּוֹרָה"
    },
    {
      "title": "B'Moza'ei Yom Menucha",
      "hebrew": "בְּמוֹצָאֵי יוֹם מְנוּחָה"
    },
    {
      "title": "Borei Minei Mezonot",
      "hebrew": "בּוֹרֵא מִינֵי מְזוֹנוֹת"
    },
    {
      "title": "Borei Minei Vesamim",
      "hebrew": "בּוֹרֵא מִינֵי בְשָׂמִים"
    },
    {
      "title": "Borei Nefashot",
      "hebrew": "בּוֹרֵא נְפָשׁוֹת"
    },
    {
      "title": "Borei Pri Ha'adamah",
      "hebrew": "בּוֹרֵא פְּרִי הָאֲדָמָה"
    },
    {
      "title": "Borei Pri Ha'etz",
      "hebrew": "בּוֹרֵא פְּרִי הָעֵץ"
    },
    {
      "title": "B'rich Sh'mei",
      "hebrew": "בְּרִיךְ שְׁמֵהּ"
    },
    {
      "title": "B'rov Am",
      "hebrew": "בְּרָב עָם"
    },
    {
      "title": "B'sefer Chayim",
      "hebrew": "בְּסֵפֶר חַיִים"
    },
    {
      "title": "B'shem Hashem",
      "hebrew": "בְּשֵׁם ה'"
    },
    {
      "title": "B'tzeit Yisrael",
      "hebrew": "בְּצֵאת יִשְׂרָאֵל"
    }
  ],
  "gimel-prayers": [
    {
      "title": "Gadelu",
      "hebrew": "גַּדְּלוּ"
    },
    {
      "title": "Gadol Ad-ai",
      "hebrew": "גָּדוֹל ה'"
    },
    {
      "title": "Gam Ki Elech",
      "hebrew": "גַּם כִּי אֵלֵךְ"
    },
    {
      "title": "Gazalnu",
      "hebrew": "גָּזַלְנוּ"
    },
    {
      "title": "G'mol Al Avd'cha",
      "hebrew": "גְּמֹל עַל עַבְדְּךָ"
    },
    {
      "title": "Gevohah Mi-kol Gevohim",
      "hebrew": "גָּבוֹהַ מִכָּל גְּבֹהִים"
    },
    {
      "title": "Gevurotecha Yechavu",
      "hebrew": "גְּבוּרוֹתֶיךָ יְחַוּוּ"
    }
  ],
  "40-0rwa": {
    "prayer-title": "Modei Ani",
    "Introduction": "Give thanks upon waking",
    "Instruction": "Said with hands clasped together",
    "prayer-id": "40-0rwa",
    "Word Mappings": {
      "0": {
        "hebrew": "מוֹדֶה אֲנִי",
        "english": "I thank",
        "transliteration": "Modeh Ani",
        "detailed-array": [
          [
            1,
            0
          ],
          [
            0,
            1
          ]
        ]
      },
      "1": {
        "hebrew": "לְפָנֶֽיךָ",
        "english": "before You",
        "transliteration": "l'fanekha",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "2": {
        "hebrew": "מֶֽלֶךְ חַי וְקַיָּם",
        "english": "King living and eternal",
        "transliteration": "melekh khai v'kayam",
        "detailed-array": [
          [
            0,
            0
          ],
          [
            1,
            1
          ],
          [
            2,
            [
              2,
              3
            ]
          ]
        ]
      },
      "3": {
        "hebrew": "שֶׁהֶחֱזַֽרְתָּ בִּי נִשְׁמָתִי",
        "english": "that You returned in me my soul",
        "transliteration": "shehechezarta bi nishmati",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ],
          [
            1,
            [
              3,
              4
            ]
          ],
          [
            2,
            [
              5,
              6
            ]
          ]
        ]
      },
      "4": {
        "hebrew": "בְּחֶמְלָה",
        "english": "with compassion",
        "transliteration": "b'chemlah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "5": {
        "hebrew": "רַבָּה אֱמוּנָתֶֽךָ",
        "english": "great is Your faithfulness",
        "transliteration": "rabbah emunatekha",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ],
          [
            1,
            [
              2,
              3
            ]
          ]
        ]
      }
    }
  },
  "50-0rwa": {
    "prayer-title": "Netilat Yadayim",
    "version": "1.0.0",
    "date_modified": "2025-08-24T04:19:54-05:00",
    "Introduction": "Blessing for washing the hands",
    "Instruction": "Recited after ritual washing of the hands, before drying them.",
    "prayer-id": "50-0rwa",
    "Word Mappings": {
      "0": {
        "hebrew": "בָּרוּךְ",
        "english": "Blessed",
        "transliteration": "Baruch",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "1": {
        "hebrew": "אַתָּה",
        "english": "You are",
        "transliteration": "atah",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "2": {
        "hebrew": "יְיָ",
        "english": "ETERNAL",
        "transliteration": "Ad-nai",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "3": {
        "hebrew": "אֱלֹהֵֽינוּ",
        "english": "our God",
        "transliteration": "Eloheinu",
        "detailed-array": [
          [
            0,
            [
              0,
              1
            ]
          ]
        ]
      },
      "4": {
        "hebrew": "מֶֽלֶךְ",
        "english": "King",
        "transliteration": "melekh",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "5": {
        "hebrew": "הָעוֹלָם",
        "english": "of the universe",
        "transliteration": "ha'olam",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "6": {
        "hebrew": "אֲשֶׁר",
        "english": "Who",
        "transliteration": "asher",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "7": {
        "hebrew": "קִדְּשָֽׁנוּ",
        "english": "has sanctified us",
        "transliteration": "kid'shanu",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "8": {
        "hebrew": "בְּמִצְוֹתָיו",
        "english": "with His commandments",
        "transliteration": "b'mitzvotav",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "9": {
        "hebrew": "וְצִוָּֽנוּ",
        "english": "and commanded us",
        "transliteration": "v'tzivanu",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "10": {
        "hebrew": "עַל",
        "english": "concerning",
        "transliteration": "al",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      },
      "11": {
        "hebrew": "נְטִילַת",
        "english": "the washing of",
        "transliteration": "netilat",
        "detailed-array": [
          [
            0,
            [
              0,
              1,
              2
            ]
          ]
        ]
      },
      "12": {
        "hebrew": "יָדָֽיִם",
        "english": "hands",
        "transliteration": "yadayim",
        "detailed-array": [
          [
            0,
            0
          ]
        ]
      }
    }
  }
};
