import { generatePrayerIndex, getOutputPath, getDateInfo } from '@mysiddur/core/custom-siddur-date-gen/generation-logic';
import { validateSiddur } from '@mysiddur/core/custom-siddur-date-gen/validation';
import * as fs from 'fs';
import * as path from 'path';

// Parse arguments
const args = process.argv.slice(2);
const daysArg = args[0] || '1-days';
const numDays = parseInt(daysArg.split('-')[0]) || 1;

console.log(`Generating Siddur layouts for the next ${numDays} days...\n`);

const baseDir = path.join(__dirname, '../../core');
const startDate = new Date();
let successCount = 0;
let failCount = 0;

for (let i = 0; i < numDays; i++) {
    const date = new Date(startDate);
    date.setDate(startDate.getDate() + i);
    
    console.log(`\n[${ i + 1}/${numDays}] Generating for: ${date.toDateString()}`);
    
    try {
        // Generate
        const index = generatePrayerIndex(date);
        
        // Validate
        const dateInfo = getDateInfo(date);
        const validation = validateSiddur(index, dateInfo);
        
        if (!validation.isValid) {
            console.error("  ❌ FAILED validation:");
            validation.errors.forEach(e => console.error(`     - ${e}`));
            failCount++;
            continue;
        }
        
        if (validation.warnings.length > 0) {
            console.warn("  ⚠️  Warnings:");
            validation.warnings.forEach(w => console.warn(`     - ${w}`));
        }
        
        // Get output path
        const outputPath = getOutputPath(date, baseDir);
        const outputDir = path.dirname(outputPath);
        fs.mkdirSync(outputDir, { recursive: true });
        
        // Write file
        const fileContent = `// This file is auto-generated by scripts/generate-siddur-layouts.ts. Do not edit manually.
// Generated for: ${date.toDateString()}
// Hebrew Date: ${dateInfo.hebrewDate.toString()}

export interface PrayerIndexEntry {
  id: string;
  title: string;
}

export interface PrayerIndexBySections {
  wakingPrayers: PrayerIndexEntry[];
  shacharis: PrayerIndexEntry[];
  mincha: PrayerIndexEntry[];
  maariv: PrayerIndexEntry[];
  retiringPrayers: PrayerIndexEntry[];
}

export const prayerIndex: PrayerIndexBySections = ${JSON.stringify(index, null, 2)};
`;
        
        fs.writeFileSync(outputPath, fileContent);
        console.log(`  ✅ Success: ${outputPath}`);
        successCount++;
        
    } catch (error) {
        console.error(`  ❌ Error: ${error}`);
        failCount++;
    }
}

console.log(`\n${'='.repeat(60)}`);
console.log(`Generation complete: ${successCount} succeeded, ${failCount} failed`);
console.log(`${'='.repeat(60)}`);
