import { generatePrayerIndex, getOutputPath, getDateInfo } from '../lib/custom-siddur-date-gen/generation-logic';
import { validateSiddur } from '../lib/custom-siddur-date-gen/validation';
import * as fs from 'fs';
import * as path from 'path';

// Parse date from command line args or use today
const args = process.argv.slice(2);
const dateStr = args[0];
const date = dateStr ? new Date(dateStr) : new Date();

console.log(`Generating Siddur for date: ${date.toDateString()}`);

// Generate
const index = generatePrayerIndex(date);

// Validate
const dateInfo = getDateInfo(date);
const validation = validateSiddur(index, dateInfo);

if (!validation.isValid) {
    console.error("\n❌ Siddur Generation FAILED 'Kosher' or 'Copesthetic' checks:");
    validation.errors.forEach(e => console.error(`  - ${e}`));
} else {
    console.log("\n✅ Siddur Generation Passed Validation.");
}

if (validation.warnings.length > 0) {
    console.warn("\n⚠️ Warnings:");
    validation.warnings.forEach(w => console.warn(`  - ${w}`));
}

// Get output path with date-organized directory structure
const baseDir = path.join(__dirname, '..');
const outputPath = getOutputPath(date, baseDir);

// Ensure directory exists
const outputDir = path.dirname(outputPath);
fs.mkdirSync(outputDir, { recursive: true });

// Write to file
const fileContent = `// This file is auto-generated by scripts/generate-siddur.ts. Do not edit manually.
// Generated for: ${date.toDateString()}
// Hebrew Date: ${dateInfo.hebrewDate.toString()}

export interface PrayerIndexEntry {
  id: string;
  title: string;
}

export interface PrayerIndexBySections {
  wakingPrayers: PrayerIndexEntry[];
  shacharis: PrayerIndexEntry[];
  mincha: PrayerIndexEntry[];
  maariv: PrayerIndexEntry[];
  retiringPrayers: PrayerIndexEntry[];
}

export const prayerIndex: PrayerIndexBySections = ${JSON.stringify(index, null, 2)};
`;

fs.writeFileSync(outputPath, fileContent);
console.log(`\nSuccessfully wrote to ${outputPath}`);
